[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = True
warn_return_any = True
warn_redundant_casts = True
warn_unused_configs = True
strict_optional = True
no_implicit_optional = True
show_error_codes = True
exclude =
    (?x)(
        ^classification-base/|
        ^covid-segmantation/|
        ^covid-segmantation/tutorials/|
        ^Surface\ Detection/|
        ^segmentation-inferance/|
        ^vllm/|
        ^vllm_training/|
        ^GAN/|
        ^lora/
    )
